### ISSUE TITLE
UI does not update after a compound model fit

### ISSUE THREAD

**Issue by ibusko** [nmearl/specviz#114]
The UI values do not update when a compound model is fitted. They do when a single model is fitted.

The reason is in line 334 in viewer.py. The _submodels attribute in a compound model instance is not updated by the fitter. The fitter only changes the top-level 'parameters' values and associated attributes. I had been banging my head myself against this same issue for quite a while now.

The way to fix this is to iterate over the compound model itself, as in 'for model in compound_model'. However, if I do this, I get again that same error in line 342 (model_item is None)

**Comment by nmearl** [comment]
See c5e2971a9332effc302793223ca9b1e3c9a8e356. The problem seems to be that a `CompoundModel` has two references to the original models:

1. `my_model[0]` is a read-only copy of the model while
2. `my_model._submodels[0]` is the original model that was used to produce the resulting compound model.

I'll have to comb through the code, but it seems there are some areas that use it one way, and other areas that use it the other way.

**Comment by nmearl** [comment]
Should be fixed now.
